config/routes.rb
SurveyRails::Application.routes.draw do
  resources :surveys do
    resources :questions do 
      resources :options 
    end
  end

  resources :responses

  root to: 'surveys#index'
end

app/models/option.rb
class Option < ActiveRecord::Base
  attr_accessible :body, :question_id

  belongs_to :question
  has_many :responses

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :survey_id, :body, :options_attributes

  belongs_to :survey
  has_many :options
  has_many :responses

  accepts_nested_attributes_for :options

end

app/models/response.rb
class Response < ActiveRecord::Base
  attr_accessible :option_id, :question_id, :option

  belongs_to :option
  belongs_to :question

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  attr_accessible :name, :questions_attributes
  has_many :questions

  accepts_nested_attributes_for :questions

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def show
    @question = Question.find(params[:id])

  end

end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController

  def create
    @response = Response.new(params[:response])
    if @response.save
      redirect_to [@response.question.survey, @response.question]
    else
      redirect_to root_path
    end
  end

  def show
    @response = Response.find(params[:id])
  end



end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  def index
  end

  def new
    @survey = Survey.new
    @survey.questions.build

    @survey.questions.each do |question|
      question.options.build
    end

  end

  def create
    @survey = Survey.new(params[:survey])

    if @survey.save
      redirect_to @survey
    else
      render "new"
    end
  end

  def show
    @survey = Survey.find(params[:id])
    @response = Response.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SurveyRails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/show.html.erb
<h2>Question:<%= @question.body  %></h2>

<% @question.options.each do |option| %>
  <p>Option: <%= option.body %> Count: <%= option.responses.count %></p>
<% end %>

app/views/surveys/index.html.erb
<h2>Angobby Survey King</h2>

<%= link_to "create survey", new_survey_path %>

app/views/surveys/new.html.erb
<h2>Create a Survey</h2>
  <div>
    <%= form_for @survey do |survey_form| %>
      <%= survey_form.label "Survey Name" %><br>
      <%= survey_form.text_field :name %>
  </div>

    <%= survey_form.fields_for :questions do |question_form| %>
      <div>
        <%= question_form.label "Question" %><br>
        <%= question_form.text_field :body %>
      </div>

        <%= question_form.fields_for :options do |option_form| %>
          <div>
            <%= option_form.label "Option" %><br>
            <%= option_form.text_field :body %>
          </div>
        <% end %>

        <%= question_form.fields_for :options do |option_form| %>
          <div>
            <%= option_form.label "Option" %><br>
            <%= option_form.text_field :body %>
          </div>
        <% end %>
    <% end %>

    <br><hr><br>

    <%= survey_form.fields_for :questions do |question_form| %>
      <div>
        <%= question_form.label "Question" %><br>
        <%= question_form.text_field :body %>
      </div>
    <% end %>

  <%= survey_form.submit %>
<% end %>

app/views/surveys/show.html.erb
<h2>Survey: <%= @survey.name %></h2>
    <% @survey.questions.each do |question| %>
    
    <h4>Question: <%= question.body %></h4>
      <ul>
        <%= form_for @response do |response_form| %>
          <%= response_form.hidden_field :question_id, value: question.id %>

         <% question.options.each do |option| %>
          <li><%= response_form.radio_button(:option_id, option.id) %><%= option.body %></li>
        <% end %>

      <%= response_form.submit "Next" %>
      </ul>
    <% end %>

<% end %>